spring:
  ai:
    openai:
      api-key: "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"
    huggingface:
      api-key: "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"
    gemini:
      api-key: "AIzaSyBdY3WnbnXRkrNynYowAYI6W7KxUl1_jNE"
    sarvam:
      api-key: "sk_qp6aaxff_wPn6kekwW8gqyYPF7u9ywE6F"
    gra:
      api-key: "test"
