spring:
  ai:
    openai:
      api-key: "YOUR_OPENAI_API_KEY"
    huggingface:
      api-key: "YOUR_HUGGINGFACE_API_KEY"
    gemini:
      api-key: "YOUR_GEMINI_API_KEY"
    sarvam:
      api-key: "YOUR_SARVAM_API_KEY"
