infisical:
  client-id: ${INFISICAL_CLIENT_ID:}
  client-secret: ${INFISICAL_CLIENT_SECRET:}
  project-id: ${INFISICAL_PROJECT_ID:397abbdb-c673-4d6e-8d8e-ed0bc928f2d6}
  environment: ${INFISICAL_ENV:dev}
  site-url: https://app.infisical.com

spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      # Embedded MongoDB will automatically start since no URI is provided.

  config:
    import: optional:file:./src/main/resources/application-local.yaml
  application:
    name: lal
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        enabled: true
    huggingface:
      api-key: ${HF_API_KEY:}
    gemini:
      api-key: ${GEMINI_API_KEY:}
      chat:
        options:
          model: gemini-1.5-flash
    grok:
      api-key: ${GROK_API_KEY:}
    sarvam:
      api-key: ${SARVAM_API_KEY:}

app:
  git:
    sync-dir: data
  users:
    nirvaan:
      password: "123"
    devaansh:
      password: "123"
    admin:
      password: "admin"
  ocr:
    tesseract-path: ${TESSERACT_PATH:/usr/bin/tesseract}
    languages: eng+hin+tel

logging:
  level:
    learn:
      lal: DEBUG
  aspect:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 6.0.5
