spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: lal
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:YOUR_OPENAI_API_KEY}
      chat:
        enabled: false
    huggingface:
      api-key: ${HF_API_KEY:YOUR_HF_API_KEY}
    gemini:
      api-key: ${GEMINI_API_KEY:YOUR_GEMINI_API_KEY}
      chat:
        options:
          model: gemini-1.5-flash
    grok:
      api-key: YOUR_GROK_API_KEY_HERE
    sarvam:
      api-key: ${SARVAM_API_KEY:YOUR_SARVAM_API_KEY}

app:
  ocr:
    tesseract-path: ${TESSERACT_PATH:/usr/bin/tesseract}
    languages: eng+hin+tel

logging:
  level:
    learn:
      lal: DEBUG
  aspect:
    enabled: true
