spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb+srv://way2csr_db_user:Ma%409701425145%23@clusterlal.txjdw5x.mongodb.net/LingoLearn?retryWrites=true&w=majority&appName=ClusterLAL
  config:
    import: optional:file:./src/main/resources/application-local.yaml
  application:
    name: lal
  ai:
    openai:
      api-key: ${OPENAI_API_KEY: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}
      chat:
        enabled: true
    huggingface:
      api-key: ${HF_API_KEY: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}
    gemini:
      api-key: ${GEMINI_API_KEY:AIzaSyBdY3WnbnXRkrNynYowAYI6W7KxUl1_jNE}
      chat:
        options:
          model: gemini-1.5-flash
    grok:
      api-key: ${GROK_API_KEY:YOUR_GROK_API_KEY_HERE}
    sarvam:
      api-key: ${SARVAM_API_KEY:src/main/resources/application-local.yaml}

app:
  users:
    nirvaan:
      password: "123"
    devaansh:
      password: "123"
    admin:
      password: "admin"
  ocr:
    tesseract-path: ${TESSERACT_PATH:/usr/bin/tesseract}
    languages: eng+hin+tel

logging:
  level:
    learn:
      lal: DEBUG
  aspect:
    enabled: true

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: shutdown
